#!/usr/bin/env python3
"""results/summary.md from results/run.json and the store.   python scripts/summarize.py [results]"""
import json
import os
import sys

import duckdb
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results")
DB = os.path.join(ROOT, "data", "derived", "xrisk.duckdb")
run = json.load(open(os.path.join(R, "run.json"), encoding="utf-8"))
con = duckdb.connect(DB, read_only=True)
out = []


def P(s=""):
    out.append(s)


def table(cols, rows):
    P("| " + " | ".join(cols) + " |"); P("|" + "---|" * len(cols))
    for r in rows:
        P("| " + " | ".join(str(c) for c in r) + " |")
    P()


def m(x, nd=1):
    return "-" if x is None else f"{x / 1e6:,.{nd}f}"


def mins(x):
    return "-" if x is None else (f"{x:.0f} s" if x < 90 else f"{x / 60:.0f} min")


days = pd.DataFrame(run["days"]); fd = days[days["fault_day"]]; cd = days[~days["fault_day"]]
P("# Results summary\n"); P("Generated by scripts/summarize.py from results/run.json and data/derived/xrisk.duckdb.\n")
P(f"Window {run['from']} to {run['to']}: {len(days)} trading days, {len(fd)} with faults injected and {len(cd)} clean, alternating. NAV ${run['config']['aum'] / 1e9:.0f}bn at the start, ${days['nav_eod'].iloc[-1] / 1e9:.3f}bn at the end. Runtime {run['runtime_s'] / 60:.0f} min on the build machine. Calendars from xops ({run['config']['xops_source']}).\n")

# ---- monitor ----------------------------------------------------------------------------------------------------------------------
mon = run["monitor"]
P("## Risk monitor under fault injection\n")
P(f"{mon['detected']} of {mon['injected']} faults detected over {mon['fault_days']} fault days ({100 * mon['detection_rate']:.1f} %), median time to detect {mins(mon['median_ttd_s'])}, p90 {mins(mon['p90_ttd_s'])}. On the {mon['clean_days']} clean days the monitor raised {mon['false_alerts_per_clean_day']:.1f} alerts a day ({mon['clean_incidents_per_day']:.1f} distinct incidents).\n")
rows = []
for t, s in sorted(mon["by_type"].items(), key=lambda kv: -kv[1]["injected"]):
    rules = con.execute("select detected_rule, count(*) n from faults where type = ? and detected_rule is not null group by 1 order by 2 desc", [t]).fetchall()
    rows.append((t, s["injected"], s["detected"], mins(s["median_ttd_s"]), mins(s["p90_ttd_s"]), ", ".join(f"{r} ({n})" for r, n in rules)))
table(["fault", "injected", "caught", "median time to detect", "p90", "caught by"], rows)
P("Alerts on clean days by rule:\n"); table(["rule", "alerts"], sorted(mon["false_alerts_by_rule"].items(), key=lambda kv: -kv[1]))
missed = con.execute("select date, type, scope from faults where detected_time is null order by date").fetchall()
if missed:
    P("Missed: " + "; ".join(f"{d} {t} {s}" for d, t, s in missed) + "\n")

# ---- book, exposures, limits ------------------------------------------------------------------------------------------------------------
P("## The book, its exposures and limits\n")
pos = con.execute("select p.strategy, i.asset_class, sum(abs(p.notional_usd)) gross, sum(p.notional_usd) net, count(*) n from positions p join instruments i using (instrument_id) where p.phase = 'EOD' and p.date = (select max(date) from positions) group by 1,2 order by 1,2").df()
table(["strategy", "asset class", "positions", "gross $m", "net $m"], [(r.strategy, r.asset_class, r.n, m(r.gross), m(r.net)) for r in pos.itertuples()])
P(f"Averages at the close over the run: gross ${days['gross'].mean() / 1e9:.2f}bn ({days['gross'].mean() / days['nav_eod'].mean():.2f} x NAV), net ${days['net'].mean() / 1e6:,.0f}m, beta-dollars ${days['beta_dollars'].mean() / 1e6:,.0f}m after the index-futures hedge, DV01 ${days['dv01'].mean():,.0f}/bp, parametric 99 % one-day VaR ${days['var_param'].mean() / 1e6:.1f}m ({100 * days['var_param'].mean() / days['nav_eod'].mean():.2f} % of NAV), historical ${days['var_hist'].mean() / 1e6:.1f}m. Daily P&L: mean ${days['pnl'].mean() / 1e6:+.2f}m, sd ${days['pnl'].std() / 1e6:.2f}m, worst ${days['pnl'].min() / 1e6:+.2f}m on {days.loc[days['pnl'].idxmin(), 'date']}; the 99 % VaR was exceeded on {int((days['pnl'] < -days['var_param']).sum())} of {len(days)} days (parametric) and {int((days['pnl'] < -days['var_hist']).sum())} (historical).\n")
lim = con.execute("select limit_name, status, count(*) n from limits group by 1,2 order by 1,2").df()
piv = lim.pivot_table(index="limit_name", columns="status", values="n", aggfunc="sum").fillna(0).astype(int).reindex(columns=["ok", "warn", "breach"]).fillna(0).astype(int)
P("Limit evaluations at the open and the close (rows are limit x scope x day):\n"); table(["limit", "ok", "warn", "breach"], [(k, r["ok"], r["warn"], r["breach"]) for k, r in piv.iterrows()])
br = con.execute("select limit_name, scope, count(distinct date) as n_days, max(utilisation) as worst from limits where status = 'breach' group by 1,2 order by 3 desc limit 8").fetchall()
if br:
    P("Most frequent breaches: " + "; ".join(f"{l}:{s} on {n} days (worst {100 * w:.0f} %)" for l, s, n, w in br) + "\n")

# ---- P&L attribution ------------------------------------------------------------------------------------------------------------------------
P("## P&L attribution\n"); pn = run["pnl"]
P(f"Total P&L ${pn['total'] / 1e6:+.1f}m over the run; the attribution reconciles to the NAV change on every day (largest gap {pn['identity_gap_max']:.4f} USD).\n")
comp = sorted(pn["by_component"].items(), key=lambda kv: kv[0])
table(["asset class : component", "$m"], [(k, f"{v / 1e6:+.2f}") for k, v in comp])
table(["strategy", "$m"], [(k, f"{v / 1e6:+.2f}") for k, v in sorted(pn["by_strategy"].items())])

# ---- margin -------------------------------------------------------------------------------------------------------------------------------------
P("## Margin and financing\n"); mg = run["margin"]
P(f"Requirement ${mg['requirement_mean'] / 1e6:,.0f}m on average against cash collateral, utilisation {100 * mg['utilisation_mean']:.0f} % on average and {100 * mg['utilisation_max']:.0f} % at worst (clean days; the margin-shortfall fault raises it above 100 % on fault days). Futures initial margin ${mg['futures_im_mean'] / 1e6:.1f}m SPAN-style against ${mg['futures_im_outrights_mean'] / 1e6:.1f}m as the sum of outright scan charges. Financing over the run ${mg['financing_total'] / 1e6:+.2f}m (cash interest less stock borrow).\n")
sr = mg["scan_ranges"]; table(["root", "price scan range $/contract", "calendar spread charge $/contract"], [(k, f"{v['scan']:,.0f}", f"{v['spread']:,.0f}") for k, v in sr.items()])

# ---- futures ------------------------------------------------------------------------------------------------------------------------------------
P("## Futures rolls\n")
rl = con.execute("select * from rolls order by date").df()
if len(rl):
    table(["date", "roll", "lots", "front", "next", "spread (ticks)", "roll P&L $/contract (positive earns the spread)", "spread observed"], [(r.date, f"{r.from_contract}->{r.to_contract}", f"{r.lots:+.0f}", f"{r.front_px:.4f}", f"{r.next_px:.4f}", f"{r.spread_ticks:+.1f}", f"{r.cost_usd / abs(r.lots):+,.0f}", "yes" if r.observed else "no (next month not listed on Yahoo)") for r in rl.itertuples()])
rs = run["rolls"]
if rs:
    table(["root", "rolls", "lots", "observed", "mean spread (ticks)", "mean roll P&L $/contract", "total $"], [(k, v["rolls"], f"{v['lots']:.0f}", v["observed"], "-" if v["spread_ticks_mean"] is None else f"{v['spread_ticks_mean']:+.1f}", "-" if v["cost_per_contract_usd"] is None else f"{v['cost_per_contract_usd']:+,.0f}", f"{v['total_cost_usd']:+,.0f}") for k, v in rs.items()])
chk = run["futures_continuous_check"]
P("Yahoo's continuous series against the listed front month (where both exist): " + "; ".join(f"{k} {v['equal']}/{v['days_both']}" for k, v in chk.items()) + ".\n")

# ---- FX ---------------------------------------------------------------------------------------------------------------------------------------------
P("## FX forwards and settlement\n"); f = run["fx"]
P(f"{f['trades']} forward trades, {f['instructions']} settlement instructions on {int(con.execute('select count(distinct value_date) from fx_settlements').fetchone()[0])} value dates; gross ${f['gross_usd'] / 1e6:,.0f}m, bilateral payment netting ${f['bilateral_usd'] / 1e6:,.0f}m, multilateral (CLS-style) ${f['multilateral_usd'] / 1e6:,.0f}m: a {100 * (f['netting_reduction'] or 0):.0f} % reduction; {f['unconfirmed']} unconfirmed at the cutoff (all on fault days, the settlement_missing fault).\n")
fxs = con.execute("select value_date, pair, ccy, counterparty, amount, confirmed from fx_settlements order by value_date, pair, ccy limit 12").fetchall()
if fxs:
    table(["value date", "pair", "ccy", "counterparty", "amount", "confirmed"], [(a, b, c, d, f"{e:,.0f}", g) for a, b, c, d, e, g in fxs])

# ---- credit ---------------------------------------------------------------------------------------------------------------------------------------
P("## Credit RFQ post-trade\n"); cr = run["credit"]
rq = con.execute("select r.*, b.fund from rfq_trades r left join (select distinct cusip, fund from read_parquet(?)) b on b.cusip = r.cusip", [os.path.join(ROOT, "data", "derived", "bonds.parquet").replace(os.sep, "/")]).df()
rows = []
for fund, g in rq.groupby("fund"):
    rows.append((f"{fund} ({'IG' if fund == 'LQD' else 'HY'})", len(g), f"{g['markup_pts'].mean():.3f}", f"{g['markup_pts'].median():.3f}", f"{g['markup_bp_yield'].mean():.1f}", f"{g['cover'].mean():.3f}", f"{g['trace_dev_pts'].mean():.3f}", int((g['trace_prints'] > 0).sum()), int((g['flags'] != '').sum())))
table(["bucket", "trades", "mean markup (pts)", "median", "mean markup (bp yield)", "mean cover (pts)", "mean dev. vs TRACE VWAP", "with prints", "flagged"], rows)
P(f"Flags: {cr['flags']}. Winning dealers: {cr['winners']}. Late TRACE reports: {cr['late_reports']} (the late_trace_report fault).\n")

# ---- checks -------------------------------------------------------------------------------------------------------------------------------------
P("## Checks\n")
ck = con.execute("select phase, check_name, status, count(*) n from checks group by 1,2,3 order by 1,2,3").df()
piv = ck.pivot_table(index=["phase", "check_name"], columns="status", values="n", aggfunc="sum").fillna(0).astype(int).reindex(columns=["ok", "warn", "fail"]).fillna(0).astype(int)
table(["phase", "check", "ok", "warn", "fail"], [(k[0], k[1], r["ok"], r["warn"], r["fail"]) for k, r in piv.iterrows()])

open(os.path.join(R, "summary.md"), "w", encoding="utf-8").write("\n".join(out)); print("wrote summary.md")
